sudo: required
dist: trusty

language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_install:
  - nvm install 10.18

install:
  - npm install

before_script:
  - travis_wait composer self-update
  - travis_wait composer install --prefer-source --no-interaction

script:
  - vendor/bin/phpunit
  - npm test

after_script:
  - vendor/bin/test-reporter
  - codeclimate < coverage/**/lcov.info

addons:
  code_climate:
    repo_token: 9f50abd103970276888567b08e665c8cedb039ee0a529ef768df269028f9d879