sudo: required
dist: trusty

language: php

php:
  - 7.4
  - 8.0
  - 8.1
  - nightly

env:
  global:
    - CC_TEST_REPORTER_ID=9f50abd103970276888567b08e665c8cedb039ee0a529ef768df269028f9d879
    - GIT_COMMITTED_AT=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git log -1 --pretty=format:%ct; else git log -1 --skip 1 --pretty=format:%ct; fi)

matrix:
  allow_failures:
    - php: nightly

before_install:
  - nvm install 18

install:
  - npm install

before_script:
  - travis_wait composer self-update
  - travis_wait composer install --prefer-source --no-interaction
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm test
  - php vendor/bin/phpunit --coverage-clover clover.xml

after_script:
  - mv tests/_output/coverage.xml clover.xml
  - ./cc-test-reporter after-build -t clover --exit-code $?